noteApp/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :users do 
    resources :notes
  end
  
  get 'signup', to: 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

noteApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

noteApp/app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user, required: true
  
    validates :title, presence: true, length: { minimum: 1 }
    validates :text, presence: true, length: { minimum: 1 }
end

noteApp/app/models/user.rb
class User < ApplicationRecord
    
    has_many :notes
    
    attr_accessor :remember_token
    
    has_secure_password
    
    before_save :email_downcase
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    validates :username, presence: true
    validates :email, presence: true, length: { maximum: 50 },
                        format: { with: VALID_EMAIL_REGEX},
                        uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 7 }
    
    
                   
                   
    
    def User.new_token
       SecureRandom.urlsafe_base64 
    end
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    
    def remember
       self.remember_token = User.new_token
       update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    def authenticated(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        self.update_attribute(:remember_digest, nil)
    end

    private
        def email_downcase 
            self.email = email.downcase 
        end     
end

noteApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

noteApp/app/controllers/notes_controller.rb
class NotesController < ApplicationController
    def index 
        @user = current_user
        @user_notes = Note.all
    end
    def new
        @user = current_user
        @user_notes = Note.all
        @user_note = Note.new
    end
    
    def create 
        @user = current_user
        
        @user_note = Note.new(note_params)
        
        @user_note = @user.notes.new(note_params)
        
        if @user_note.save
            redirect_to user_notes_path(@user_note)
        else 
            render 'new'
        end
        
    end
    
    def show 
        @user = current_user
        @user_notes = Note.all
        @user_note = Note.find(params[:id]) 
    end
    
    def edit 
        @user = current_user
        @user_notes = Note.all
        @user_note = Note.find(params[:id])
    end
    
    def update 
        @user = current_user
        @user_note = Note.find(params[:id])
        if @user_note.update(note_params)
            redirect_to user_notes_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @user_notes = Note.all
        @user_note = Note.find(params[:id])
        @user_note.destroy
        
        redirect_to user_notes_path
    end
    
end

private 
 def note_params
    params.require(:note).permit(:title, :text)
 end

noteApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new 
        
    end
    
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        
        if user && user.authenticate(params[:session][:password])
           
           login(user)
           
           params[:session][:remember_me]  == '1' ? remember(user) : forget(user)
           
           redirect_to user_notes_path(user.id)
        else 
            flash[:danger] = "Invalid email or password"
            render 'new'
        end
         
    end
    
    def destroy
        logout  if sign_in?
        
        redirect_to login_path
        
    end
    
    
end

noteApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
       @user = User.new 
    end
    
    def create 
        
        @user = User.new(user_params)
        
        if @user.save
            login(@user) #login after sign up
            flash[:success] = "Sign Up successfully"
            redirect_to user_notes_path(@user)
        else
            if (@user.password != @user.password_confirmation)
                flash[:error] = "Password Does not match"
            else 
                flash[:error] = "Fill the missing fields"
                
            end
            render 'new'
        end
        
    end
    
    def show 
        @user = current_user
        redirect_to user_notes_path(@user)
        
    end
    
end
private 
 def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
 end
 
 def find_user
    @user = User.find(params[:id]) 
 end

noteApp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

noteApp/app/helpers/application_helper.rb
module ApplicationHelper
end

noteApp/app/helpers/notes_helper.rb
module NotesHelper
end

noteApp/app/helpers/sessions_helper.rb
module SessionsHelper
    def login(user)
        session[:user_id] = user.id
    end
    
    
    def remember(user)
       user.remember
       cookies.permanent.signed[:user_id] = user.id
       cookies.permanent.signed[:remember_token] = user.remember_token
       
    end
    
    
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
        
    end
    
    def current_user
        if(user_id = session[:user_id])
            @current_user = User.find_by(id: user_id)
        else (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                login user
                @current_user = user
                
            end
        end
       
    end
    
    def sign_in?
        !(current_user.nil?)
    end
    
    def logout
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    
end

noteApp/app/helpers/users_helper.rb
module UsersHelper
end

noteApp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

noteApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://i.icomoon.io/public/temp/34137a2e71/UntitledProject/style.css">
    
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <div class = "header-container">
          <div class = "logo">
              <img src = <%= asset_path('logo.png') %> alt = "Logo"/>
          </div>
          <div class = "user-name">
              <% if sign_in? %>
                <%= link_to current_user.username, user_path(current_user.id) %>
                <%= link_to 'Logout', logout_path(current_user.id), method: :delete, data: { confirm: 'Are you sure?' } %>
              <% else %>
                <%= link_to 'Login', login_path %>
                <%= link_to 'Signin', signup_path %>
              <% end %>
          </div>
        </div>
    </header>
    <%= yield %>
  </body>
</html>

noteApp/app/views/notes/_form.html.erb
<%= form_for :note, url: user_notes_path do |f| %>
            
    <%= f.text_field :title, placeholder: "Note Title", :required => true %>
    <ul id = "notepad-fuction">
        <li><a href = "#" id = "text-bold" ><span class="icon-format-bold"></span></a></li>
        <li><a href = "#" id = "text-intalic"><span class="icon-format-italic"></span></a></li>
        <li><a href = "#" id = "text-underline" ><span class="icon-format-underline"></span></a></li>
    </ul>
            
    <%= f.text_area :text, placeholder: "Your note here.... ", :required => true %>
            
    <%= f.submit value: "Save Note" %>
            
<% end %>

noteApp/app/views/notes/_note_list_container.html.erb
<!-- Note list container -->
    <div class = "note-list-container">
        <ul id = "note-list-fuction">
            <li><%= link_to '', new_user_note_path, class: 'icon-add-outline' -%></li>
            <li><%= link_to '', user_note_path(@user.id, @user_note), method: :delete, data: { confirm: 'Are you sure?' }, class: "icon-trash" %></li>
        </ul>
        
        <div class = "search">
            <input id = "search" name = "search" type = "text" placeholder = "Search" />
        </div>
        <div class = "note-list">
            <ul>
                <% @user.notes.reverse_each do |note| %>
                    <li>
                        <% if (note.title == @user_note.title && note.text ==  @user_note.text) %>
                            <%= link_to note.title, user_note_path(@user.id, note), :class=> "active" %>
                        <% else %>
                            <%= link_to note.title, user_note_path(@user.id, note) %>
                        <% end %> 
                    </li> 
                <% end %>
                
            </ul>
        </div>
    </div>

noteApp/app/views/notes/edit.html.erb
<div class = "note-app-container" >
    <!-- Note list container -->
    <%= render 'note_list_container' %>
    
    
    <!-- Note Display container -->
    <div class = "note-display-container">
        
        <%= render 'form' %>
        
    </div>
</div>

noteApp/app/views/notes/index.html.erb
<div class = "note-app-container" >
    <!-- Note list container -->
    <div class = "note-list-container">
        <ul id = "note-list-fuction">
            <li><%= link_to '', new_user_note_path, class: 'icon-add-outline' -%></li>
            <li><a href = "#" id = "deleteNote" ><span class="icon-trash"></span></a></li>
        </ul>
        
        <div class = "search">
            <input id = "search" name = "search" type = "text" placeholder = "Search" />
        </div>
        <div class = "note-list">
            <ul>
                <% @user.notes.reverse_each do |note| %>
                    <li>
                      <%= link_to note.title, user_note_path(@user.id, note) %>
                    </li> 
                <% end %>
                
            </ul>
        </div>
    </div>
    
    
    <!-- Note Display container -->
    <div class = "note-display-container">
        
    </div>
</div>

noteApp/app/views/notes/new.html.erb
<div class = "note-app-container" >
    <!-- Note list container -->
    <div class = "note-list-container">
        <ul id = "note-list-fuction">
            <li><%= link_to '', new_user_note_path, class: 'icon-add-outline' -%></li>
            <li><a href = "#" id = "deleteNote" ><span class="icon-trash"></span></a></li>
        </ul>
        
        <div class = "search">
            <input id = "search" name = "search" type = "text" placeholder = "Search" />
        </div>
        <div class = "note-list">
            <ul>
                <% @user.notes.reverse_each do |note| %>
                    <li>
                      <%= link_to note.title, user_note_path(@user.id, note) %>
                    </li> 
                <% end %>
                
            </ul>
        </div>
    </div>
    
    
    <!-- Note Display container -->
    <div class = "note-display-container">
        
        <%= render 'form' %>
        
    </div>
</div>

noteApp/app/views/notes/show.html.erb
<div class = "note-app-container" >
    
    <%= render 'note_list_container' %>
    
    <!-- Note Display container -->
    <div class = "note-show-container">
        
        <h3>
           <%= @user_note.title %>
        </h3>

        <p>
            <%= @user_note.text %>
        </p>
        
        <div class = "edit-delete-container">
            <%= link_to 'Edit Note', edit_user_note_path(@user.id, @user_note) %>
            <%= link_to 'Delete Note',  user_note_path(@user.id, @user_note), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
</div>

noteApp/app/views/users/new.html.erb
<h1 class = "text-center"> Sign Up </h1>
    
    <% flash.each do |key, message| %>
        <div> <%= message %></div>
    <% end %>
    
    <%= form_for(@user) do |f| %>
        <div class = "form-group">
            <%= f.text_field :username, placeholder: "username" %>
        </div>
        
        <div class = "form-group">
            <%= f.email_field :email, placeholder: "email" %>
        </div>
        
        <div class = "form-group">
            <%= f.password_field :password, placeholder: "password" %>
        </div>
        
        <div class = "form-group">
            <%= f.password_field :password_confirmation, placeholder: "confirm password" %>
        </div>
       
        <div class = "form-group">
           <%= f.submit "Create an account" %>
        </div>
        
        
        <%= link_to 'Already have an account', 'login' %>
    <% end %>
    
    
    
    <%= yield %>

noteApp/app/views/users/show.html.erb
<% flash.each do |key, message| %>
        <div class = "message-<%= key %>" > <%= message %>></div>
    <% end %>
    
    
    

noteApp/app/views/welcome/index.html.erb
<div id="element" class="introLoading"></div>
    
<div class = "title">
    <h1>Welcome to Note Taking App</h1>
    <%= link_to 'Click here to signup', '/signup' %>
    <%= link_to 'Already have an account', '/login' %>
    
</div>